spring:
  h2:
    console:
      enabled: true
  datasource:
    url: ${testDbUrl}
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop