name: ci-test.yml

on:
  workflow_dispatch:

jobs:
  disabled:
    name: 코드 테스트 비활성화
    runs-on: ubuntu-latest
    if: ${{ false }}
    steps:
      - run: echo "ci-test workflow is temporarily disabled."
